export const API = {
  'API': 'http://localhost:8000/api',
  'LOGIN': 'http://localhost:8000/api/.user/login',
  'INSCRIPTION': 'http://localhost:8000/api/.user/inscription',
  'VALIDATION': 'http://localhost:8000/api/.user/inscription/valide-user',
  'FUTURE_USERS': 'http://localhost:8000/api/.user/future-users',
  'USER': 'http://localhost:8000/api/.user/user',
  'USERS': 'http://localhost:8000/api/.user/users',
  'CHECK_ROLE': 'http://localhost:8000/api/.user/checkRole',
  'CAR_LIST': 'http://localhost:8000/api/.car/car',
  'CAR_DETAIL': 'http://localhost:8000/api/.car/car/:id',
  'CREATE_CAR': 'http://localhost:8000/api/.car/car/create',
  'UPDATE_CAR': 'http://localhost:8000/api/.car/car/update/:id',
  'DELETE_CAR': 'http://localhost:8000/api/.car/car/delete/:id',
}